### ISSUE TITLE
jupyter-tikz in jupyter notebooks (VSCode) using TinyTex

### ISSUE THREAD

**Issue by skwde** [lucaslrodri/jupyter-tikz#7]
When I try to render the example given at your gettings started page after loading the extension

```python
%load_ext jupyter_tikz
```

```py
%%tikz
\begin{tikzpicture}
    \draw[help lines] grid (7, 5);
     \filldraw [color=red, opacity=0.3] (2.5,2.5) circle (1.5);
     \filldraw [color=cyan, opacity=0.3] (4.5,2.5) circle (1.5);
\end{tikzpicture}
```

I get 

```sh
/bin/sh: 1: pdflatex: not found
```

My Setup:

- I use TinyTex (https://yihui.org/tinytex/ / https://github.com/rstudio/tinytex) as my latex distribution and have `pdflatex` on my `PATH` and `pgf` installed
- I run the jupyter notebook inside VSCode
- I run everything inside a devcontainer (debian bookworm) on a Mac

**Comment by lucaslrodri** [comment]
For reasons I can't quite explain, VS Code and Jupyter TikZ encounter some issues; for me, it freezes when the TikZ code causes an error. However, you can run a local Jupyter Lab server and use it in VS Code.

Instructions:

1. Open the terminal and type:
```bash
jupyter lab # 'conda install -c conda-forge jupyterlab' if you don't have it
```
2. Copy the server address, which will be something like:
```
http://localhost:8888/lab?token=dc2157ee1f51bb6c73dab330821a557cffb67f62daa929a4
```
3. Open your ipynb file
4. Press `Ctrl+Shift+P` and type `Notebook: Select Notebook Kernel`
5. Select `Existing Jupyter Server` and paste the address of your local server.

Test it out and let me know if it's working.

**Comment by skwde** [comment]
@lucaslrodri thanks for the suggestion of a workaround using jupyter lab.

Ok, in your case it freezes, in my case it didn't find `pdflatex`. 

I actually just found the problem, it was related to using `~` to specify the path to `pdflatex` in `PATH`.

Now it just runs fine.

I tried to reproduce the freeze, but it just continues running until I interrupt the kernel.
Putting `%%tikz -as=t -e` (as mentioned doesn't change anything <https://jupyter-tikz.readthedocs.io/stable/usage/as-magic/#logging-and-debugging>).

**Comment by lucaslrodri** [comment]
@skwde 

Great that you figured out the problem yourself :tada: 

Here's another tip: you can specify a custom pdflatex PATH using the `-tp=<tex_program>` parameter.
 
Here's an example for Windows (this approach might work on other systems as well):

```python
# Replace with your custom PATH
PDFLATEX_PATH = r"C:\Users\lucas\AppData\Local\Programs\MiKTeX\miktex\bin\x64\pdflatex.exe"
```

```latex
%%tikz -as=tikz -t=pgfplots -nt -tp="$PDFLATEX_PATH"
\begin{axis}[
  xlabel=$x$,
  ylabel={$f(x) = x^2 - x + 4$}
]
\addplot {x^2 - x + 4};
\end{axis}
```

Feel free to test this alternative and let me know how it works for you.

If this solution proves effective, I’ll consider adding it to the documentation as an alternative for those encountering `pdflatex` path issues.
